[build]
  command = "npm run build"
  publish = "dist"
  base = "ProvaSandro/landing_page"
  functions = "netlify/functions" # O Netlify buscará aqui na raiz

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200